site_name: brusbilis
site_favicon: 'z-static/images/logo/brusbb.png'
google_analytics: ['UA-65859401-3', 'auto']
extra:
    logo: 'z-static/images/logo/brusbb.png'

pages:
- MENU :
    - 'Menu Chuletas': 'index.md'
- FRONT-END:
    - 'html5': 'frontend/html5.md'
    - 'css3': 'frontend/css3.md'
    - 'javascript': 'frontend/js.md'
    - 'jQuery': 'frontend/jquery.md'
    - 'trucos frontend': 'frontend/frontendTips.md'
- BACK-END:
    - 'node.js': 'backend/nodejs.md'
    - 'bases de datos': 'backend/bbdd.md'
    - 'golang': 'backend/golang.md'
    - 'trucos backend': 'backend/backendTips.md'
- VARIOS:
    - 'debian': 'varios/debian.md'
    - 'macOS': 'varios/macOS.md'
    - 'git, mkDocs, expReg': 'varios/varios1.md'

markdown_extensions:
    - fenced_code

theme_dir: 'brus-docs-theme'
site_dir: 'chuletas'
docs_dir: 'docs/content'
extra_css:
    - 'z-static/extra.css'
