site_name: brusbilis
#site_favicon: 'z-static/images/favicon.png'
site_favicon: 'z-static/images/logo/brusbb.png'
google_analytics: ['UA-65859401-3', 'auto']
extra:
    logo: 'z-static/images/logo/brusbb.png'

pages:
- MENU CHULETAS: 'index.md'
- FRONT-END:
    - 'html5': 'frontend/html5.md'
    - 'css3': 'frontend/css3.md'
    - 'javascript I': 'frontend/js1.md'
    - 'javascript II': 'frontend/js2.md'
    - 'javascript APIs': 'frontend/apis.md'
    - 'jQuery': 'frontend/jquery.md'
- BACK-END:
    - 'node.js': 'backend/nodejs.md'
    - 'express': 'backend/express.md'
    - 'node.js realtime': 'backend/realTime.md'
    - 'npm modulos': 'backend/npm1.md'
    - 'bases de datos': 'backend/bbdd.md'
    - 'meteor': 'backend/meteor.md'
    - 'golang': 'backend/golang.md'

- VARIOS:
    - 'debian testing': 'varios/testing.md'
    - 'debian servidor': 'varios/servidor.md'
    - 'macOS': 'varios/macOS.md'
    - 'git, mkDocs, expReg': 'varios/varios1.md'

markdown_extensions:
    - fenced_code

theme_dir: 'brus-docs-theme'
site_dir: 'chuletas'
docs_dir: 'docs/content'
extra_css:
    - 'z-static/extra.css'
