site_name: Chuletas
google_analytics: ['UA-65859401-3', 'auto']
repo_url: https://github.com/brusbilis/chuletas
strict: true
extra:
    logo: '_img/logo/brusbb.png'
    #logo_name: false
    include_toc: false
    extra_nav_links:
        #volver a la pagina principal : "https://brusbilis.com"

pages:
- MENU :
    - 'Menu Chuletas': 'index.md'
- CLIENTE:
    - 'html y css': 'cliente/html-css.md'
    - 'javascript': 'cliente/javascript.md'
    - 'javascript para web': 'cliente/javascript-web.md'
    - 'javascript apis': 'cliente/javascript-apis.md'
    - 'jQuery': 'cliente/jquery.md'
    - 'recursos cliente': 'cliente/recursos-cliente.md'
- SERVIDOR:
    - 'node.js': 'servidor/nodejs.md'
    - 'express.js': 'servidor/expressjs.md'
    - 'golang': 'servidor/golang.md' 
    - 'golang para web': 'servidor/golang-web.md'
    - 'bases de datos': 'servidor/bases-datos.md'
    - 'recursos servidor': 'servidor/recursos-servidor.md'
- VARIOS:
    - 'debian y macos': 'varios/debian.md'
    - 'imagemagick, git, mkdocs': 'varios/varios.md'
    - 'expresiones regulares': 'varios/expresiones-regulares.md'

markdown_extensions: 
    - fenced_code

theme_dir: 'brus-docs-theme'
#theme: alabaster
site_dir: 'chuletas'
docs_dir: 'docs'
extra_css:
    - '_extra/css/extra.css'
    #- '_extra/css/atom-one-light.css'
    #- '_extra/js/highlight.pack.js'
 




