site_name: brusbilis
#site_favicon: 'z-static/images/favicon.png'
site_favicon: 'z-static/images/logo/brusbb.png'
google_analytics: ['UA-65859401-3', 'auto']
extra:
    logo: 'z-static/images/logo/brusbb.png'

pages:
- Menu Chuletas: 'index.md'
- Front-end:
    - 'Html5': 'frontend/html5.md'
    - 'CSS3': 'frontend/css3.md'
    - 'Javascript I': 'frontend/js1.md'
    - 'Javascript II': 'frontend/js2.md'
    - 'Javascript APIs': 'frontend/apis.md'
    - 'jQuery': 'frontend/jquery.md'
- Back-End:
    - 'NodeJS': 'backend/nodejs.md'
    - 'Express': 'backend/express.md'
    - 'Bases de Datos': 'backend/bbdd.md'
    - 'Tiempo Real': 'backend/tiempoReal.md'
    - 'Modulos': 'backend/modulos1.md'
    - 'Meteor': 'backend/meteor.md'
    - 'Golang': 'backend/golang.md'
- Debian:
    - 'Testing': 'debian/testing.md'
    - 'Servidor': 'debian/servidor.md'
- Varios:
    - 'Varios I': 'varios/varios1.md'

markdown_extensions:
    - fenced_code

theme_dir: 'brus-docs-theme'
site_dir: 'chuletas'
docs_dir: 'docs/content'
extra_css:
    - 'z-static/extra.css'
