site_name: Chuletas
google_analytics: ["UA-114956807-1", "auto"]
repo_url: https://github.com/jolav/chuletas
strict: true

nav:
  - 'Menu': 'index.md'
  - 'HTML': 'html.md'  
  - 'CSS': 'css.md'
  - 'Front End': 'frontend.md'
  - 'Javascript': 'javascript.md'  
  - 'Javascript APIs': 'javascript-apis.md'
  - 'Javascript para web': 'javascript-para-web.md'
  - 'Javascript snippets': 'javascript-snippets.md'
  - 'Reactjs': 'reactjs.md'
  - 'Nodejs': 'nodejs.md' 
  - 'Expressjs': 'expressjs.md'
  - 'Nodejs snippets': 'nodejs-snippets.md'
  - 'Nodejs Bases de Datos': 'nodejs-bases-de-datos.md'
  - 'Golang': 'golang.md'
  - 'Golang para web': 'golang-para-web.md'
  - 'Golang snippets': 'golang-snippets.md'
  - 'Golang Bases de Datos': 'golang-bases-de-datos.md'
  - 'C#': 'csharp.md'
  - '.Net Core': 'dotnet-core.md'
  - 'Debian': 'debian.md'
  - 'Varios': 'varios.md'

#theme: alabaster
#theme_dir: "chuletas-theme"
theme:
  name: alabaster
  custom_dir: chuletas-theme
site_dir: 'chuletas'
docs_dir: 'docs'
extra_css:
- '_extra/css/extra.css'
extra_javascript:
- '_extra/js/highlight.pack.js'
extra:
  logo: '_img/chuletas128.png'
  include_toc: true

